on:
  push:
    branches:
    - master
  pull_request:

name: xbuild

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace --examples --tests --all-features -- -D warnings
    - run: cargo test

  build:
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
    - run: cargo install --path xbuild --root .
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.host }}-x
        path: bin/x${{ matrix.host == 'windows-latest' && '.exe' || '' }}
